apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudwatch-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: cloudwatch-exporter
  namespaceSelector:
    matchNames:
      - cloudwatch-exporter
  endpoints:
    - port: metrics
      interval: 60s